version: "3.7"

services:
  web:
    build: '.'
    expose:
      - 9003
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/
    # environment:
      # XDEBUG_MODE: develop,debug

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
            - ./hits.csv:/var/lib/mysql-files/hits.csv
    environment:
      MYSQL_ROOT_PASSWORD: root
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

      